-- Jalankan di Supabase: SQL Editor > New query > paste > Run
create table if not exists public.perjanjian_vendor (
  id uuid primary key default gen_random_uuid(),
  jenis text not null check (jenis in ('Outsourcing','Sewa Kendaraan')),
  no_perjanjian text not null,
  vendor_nama text not null,
  vendor_pic text,
  vendor_kontak text,
  departemen text,
  tgl_mulai date not null,
  tgl_akhir date not null,
  nilai numeric default 0,
  periode_bayar text default 'Bulanan',
  -- khusus Outsourcing
  jumlah_tenaga integer,
  posisi text,
  -- khusus Sewa Kendaraan
  tipe_kendaraan text,
  jumlah_unit integer,
  no_polisi text,
  dengan_driver text,
  link_dokumen text,
  keterangan text,
  created_by text,
  created_at timestamptz default now()
);

-- Kolom tambahan: pengguna kendaraan & rantai perpanjangan
alter table public.perjanjian_vendor add column if not exists pengguna text;
alter table public.perjanjian_vendor add column if not exists perpanjangan_ke integer default 0;
alter table public.perjanjian_vendor add column if not exists induk_id uuid references public.perjanjian_vendor(id) on delete set null;

-- Aplikasi memakai anon key (sama seperti tabel lain), jadi izinkan akses anon.
alter table public.perjanjian_vendor enable row level security;
drop policy if exists "akses_anon_perjanjian_vendor" on public.perjanjian_vendor;
create policy "akses_anon_perjanjian_vendor" on public.perjanjian_vendor
  for all to anon using (true) with check (true);


-- ===== Master Area =====
create table if not exists public.master_area (
  id bigint generated by default as identity primary key,
  kode_area text not null unique,
  nama_area text not null,
  created_by text,
  created_at timestamptz default now()
);
alter table public.master_area enable row level security;
drop policy if exists "akses_anon_master_area" on public.master_area;
create policy "akses_anon_master_area" on public.master_area for all to anon using (true) with check (true);

-- Kolom area (opsional) pada karyawan & perjanjian sewa kendaraan
alter table public.master_karyawan add column if not exists area text;
alter table public.perjanjian_vendor add column if not exists area text;
